### ISSUE TITLE
Is there a way to specify the country? 

### ISSUE THREAD

**Issue by ben1one** [damonwonghv/youtube-search-api#16]
When I use it in localhost it is perfect. But when I deploy to GIthub action and run it, it doesn't give the same content. Would be very useful to get local contents for users. I tried add `&persist_gl=1&gl=HK` and no hope.

**Comment by damonwonghv** [comment]
> This seem to be working
> 
> ```
> 
> const page = await axios.get(encodeURI(url)+"&persist_hl=1&hl=ja&persist_gl=1&gl=JP");
> 
> ```

Apology for the late reply, I will test it, if work fine, I will put it in next release.

**Comment by damonwonghv** [comment]
Not really work, since location change only works when you use VPN or proxy, Youtube does not allow you to change your real location via some easy config (query=JP), so I think no workaround solution at this moment. Maybe I will make a Docker container to allow easy switch location by proxy or other technic.
